### ISSUE TITLE
Make freyja deboot optional?

### ISSUE THREAD

**Issue by mish-su** [CDCgov/aquascope#13]
Great pipeline! 

At least for my samples, freyja deboot takes ages to run. It takes so long that it was running into 16 hour time limits, so I had to modify the configs to let it run longer. Even then, the time is a bit of an issue: a MiSeq run of 2.8 Gb was taking 2 full days to run on a 40 core server. 

For right now, I've just commented out freyja deboot and am relying on other QC metrics like coverage and depth. I imagine others might do the same as there is very little guidance on how to incorporate freyja deboot output into quality control.

Just a thought!

**Comment by arunbodd** [comment]
This is an issue we are facing too with freyja boot since it runs 1000 bootstraps (by default) and its run to confidently confirm the variants researchers are seeing from the freyja demix. We have tested it rigorously on simulated datasets and seems like freyja demix can be sufficient enough, but I'd approach the results with caution since its case by case basis.

**Comment by slsevilla** [comment]
Removed in previous version
